#!/bin/bash

export PATH=$PATH:/opt/gromacs-2019/bin/
#source /usr/local/gromacs/bin/GMXRC
#export PATH=/scratch/gromacs-2020/build/bin:$PATH

NAME=$1

#echo 3 1 | gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_md.xtc -o output/"$NAME"_nopbc_cluster.xtc -pbc cluster
#echo 3 1 | gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_nopbc_cluster.xtc -o output/"$NAME"_nopbc_cluster_fit.xtc -fit rot+trans
gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_md.xtc -o output/"$NAME"_nopbc_cluster.xtc -pbc cluster
gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_nopbc_cluster.xtc -o output/"$NAME"_nopbc_cluster_fit.xtc -fit rot+trans
#echo 3 1 | gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_nopbcrottrans.xtc -o output/"$NAME"_md_cluster.xtc -pbc cluster

# cluster
#echo 3 1 | gmx trjconv -s output/"$NAME"_md.tpr -f output/"$NAME"_md.xtc -o output/"$NAME"_md_cluster.xtc -pbc cluster -ur compact


